In [1]:
import torch
import numpy as np

c:\Users\dodo7\miniconda3\envs\lesa4\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


reshape과 view, 둘다 똑같은기능, 얕은복사라는점도 같다


In [3]:
z = torch.zeros(3, 2,5,2)
x = z.view(2,-1,2)
# z.fill_(2.1)
# print(f'view 적용: {x}')
x.shape

torch.Size([2, 15, 2])

In [2]:
z = torch.zeros(3, 2)
x = z.view(1,6)
z.fill_(2.1)
print(f'view 적용: {x}')

view 적용: tensor([[2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000]])


In [3]:
z = torch.zeros(3, 2)
x = z.reshape(1,6)
z.fill_(2.1)
print(f'reshape 적용: {x}')

reshape 적용: tensor([[2.1000, 2.1000, 2.1000, 2.1000, 2.1000, 2.1000]])


squeeze와 unsqueeze

squeeze: 차원이 1인경우 해당차원을 제거한다(1인차원이 여러개라도 상관없음)

unsqueeze: 특정위치에 1인 차원을 추가한다(인덱스 기준, 인덱스에 맞게 입력하지않으면 에러가 발생한다, -1을 넣으면 마지막 차원에 1을 추가함)

In [21]:
ft = z = torch.zeros(3,1,3)
print(ft.shape)

torch.Size([3, 1, 3])


In [23]:
print(ft.squeeze().shape)
print(ft.unsqueeze(3).shape)
print(ft.reshape(3,1,3,1).shape) # shape으로도 가능하다

torch.Size([3, 3])
torch.Size([3, 1, 3, 1])
torch.Size([3, 1, 3, 1])


타입 변경하는법: .타입() 

In [29]:
lt = torch.LongTensor([1.1, 2.3, 3.6, 4,])
print(lt)

tensor([1, 2, 3, 4])


In [30]:
print(lt.float())
print(lt.double())
print(lt.int())

tensor([1., 2., 3., 4.])
tensor([1., 2., 3., 4.], dtype=torch.float64)
tensor([1, 2, 3, 4], dtype=torch.int32)


연결하기 cat(어떤차원과 연결할것인지 dim을통해 결정할수있다)

In [31]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [32]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


stacking: concat하는 또다른 방법

In [34]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


ones_like와 zeros_like 0과 1로 채워진 텐서

In [36]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


연산뒤에_를 붙여 덮어쓰기연산을 할수있다

In [38]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [39]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
