간단하게 집고넘어가는 선형회귀이다

https://wikidocs.net/53560
1. 가설수립: feature를 받아서 y를 예측하는 과정에 있어서 그 방법론들을 말하는것같다 이번에 써볼것은 선형회귀이다
2. 비용함수: 실제 예측값과 오차를 계산하는 함수이다 loss function 즉 손실함수라고도 많이 불리는것같다 mse를 사용하셨는데 모든 오차를 제곱한다음에 평균을 구하는 방식이다 그러면 아무리봐도 제곱평균오차가 맞는것같다....
3. 옵티마이저 - 경사 하강법(Gradient Descent): 경사하강법은 가장 기초적인 최적화 알고리즘이라고 한다  비용함수를 미분하여 접선의 기울기기가 낮은 방향으로 w및 b(선형회귀)값을 변경하는것이다 여기서 궁금증은 기울기가 0인지점이 여러개 있을경우 어떻게 되는지인데 이것은 후에 더 자세하게 알아보자 지금은 원활한 대회참여를 위한 제대로된 파이토치 공부가 급하다(너무늦은감이 있긴하지만 이제서야 필요성을 느낀것같다)
4. 학습률이란 경사하강법으로 최적인 w,b값을 찾는 과정에서 얼마나 큰폭으로 이동할건지를 의미 너무 크면 제대로된값을 찾을수없다

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

c:\Users\dodo7\miniconda3\envs\lesa4\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드(random seed)를 줍니다.
torch.manual_seed(2023) # 딥러닝에서 random num을 사용하는경우가 많다라고함

변수선언(이제 시작이다)

In [9]:
X_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

가중치와 편향의 초기화

In [10]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True) 
# 가중치 W를 출력
print(W) 

tensor([0.], requires_grad=True)


In [11]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


지금 가설에서는 어떤값이 들어가도 가설은 0을 예측 이는 적절한 w와 b값이 아님 오차함수에 기반한 적절한 수정이 필요하다

In [12]:
hypothesis = X_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


손실함수 선언

In [13]:
# 앞서 배운 torch.mean으로 평균을 구한다.
cost = torch.mean((hypothesis - y_train) ** 2) 
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


경사하강법 구현

In [14]:
optimizer = optim.SGD([W, b], lr=0.01)

In [15]:
# gradient를 0으로 초기화 (cost의 최저점을 찾는 과정에서 모든 가중치를 0으로 초기화시키는것으로 이해했다)
optimizer.zero_grad() 
# 비용 함수를 미분하여 gradient 계산
cost.backward() 
# W와 b를 업데이트
optimizer.step() 

In [16]:
print(W)
print(b)

tensor([0.1867], requires_grad=True)
tensor([0.0800], requires_grad=True)


전체코드(에폭추가)

In [19]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad() # 전루프의 gradient 값에 영향을 받지않기위해 새롭게 시작하는거라고 이해했다 어차피 가중치들이 업데이트되면 새로운 비용함수를 미분하게되는데 예전의 gradient값을 가지고가는게 의미없을것같기도하다
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

이번에는 다중선형회귀이다 행렬곱을 사용하여 여러개의 가중치들을 하나하나 변수로 등록할필요가 없이 한번에 계산할수있다

In [32]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b # 가중치와 x_train의 행렬곱

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670898
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.482086
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

해당실습을 통해 알게된것

먼저 예측을 하고 그것에 대한 손실을 계산해 가중치를 수정한다 정도가 내가 원래 알고있던 상식인데 

아직도 안다고 말할수는 없는 수준이지만 왜 행렬이 딥러닝에 필요한지 그리고 가중치 수정은 어떤 방식으로 이루어지는지 다시한번 생각해볼수있는 기회가 되었던것같다(더 머리속이 복잡해졌다 사실상 새로 알게된건 없을지도)


nn.Module로 구현

In [33]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(2023)


In [34]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [35]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)

In [36]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [37]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 17.833910
Epoch  100/2000 Cost: 0.118925
Epoch  200/2000 Cost: 0.073488
Epoch  300/2000 Cost: 0.045411
Epoch  400/2000 Cost: 0.028061
Epoch  500/2000 Cost: 0.017340
Epoch  600/2000 Cost: 0.010715
Epoch  700/2000 Cost: 0.006621
Epoch  800/2000 Cost: 0.004092
Epoch  900/2000 Cost: 0.002528
Epoch 1000/2000 Cost: 0.001562
Epoch 1100/2000 Cost: 0.000965
Epoch 1200/2000 Cost: 0.000597
Epoch 1300/2000 Cost: 0.000369
Epoch 1400/2000 Cost: 0.000228
Epoch 1500/2000 Cost: 0.000141
Epoch 1600/2000 Cost: 0.000087
Epoch 1700/2000 Cost: 0.000054
Epoch 1800/2000 Cost: 0.000033
Epoch 1900/2000 Cost: 0.000021
Epoch 2000/2000 Cost: 0.000013


In [38]:
# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]]) 
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y) 

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9929]], grad_fn=<AddmmBackward0>)


In [39]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9959]], requires_grad=True), Parameter containing:
tensor([0.0094], requires_grad=True)]


1. 데이터정의
2. 모델정의
3. 옵티마이저 정의 # 경사하강법 방식
4. 손실함수 정의

클래스로 구현하기(이부분을 배우고 싶었다)

In [41]:
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 파이썬 클래스
    def __init__(self): #
        super().__init__()
        self.linear = nn.Linear(1, 1) # 단순 선형 회귀이므로 input_dim=1, output_dim=1.

    def forward(self, x): #  입력 X로부터 예측된 y를 얻는 것을 forward 연산이라고 합니다.
        return self.linear(x)

In [42]:
model = LinearRegressionModel()

In [43]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [44]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 5.866064
Epoch  100/2000 Cost: 0.012314
Epoch  200/2000 Cost: 0.007609
Epoch  300/2000 Cost: 0.004702
Epoch  400/2000 Cost: 0.002906
Epoch  500/2000 Cost: 0.001796
Epoch  600/2000 Cost: 0.001110
Epoch  700/2000 Cost: 0.000686
Epoch  800/2000 Cost: 0.000424
Epoch  900/2000 Cost: 0.000262
Epoch 1000/2000 Cost: 0.000162
Epoch 1100/2000 Cost: 0.000100
Epoch 1200/2000 Cost: 0.000062
Epoch 1300/2000 Cost: 0.000038
Epoch 1400/2000 Cost: 0.000024
Epoch 1500/2000 Cost: 0.000015
Epoch 1600/2000 Cost: 0.000009
Epoch 1700/2000 Cost: 0.000006
Epoch 1800/2000 Cost: 0.000003
Epoch 1900/2000 Cost: 0.000002
Epoch 2000/2000 Cost: 0.000001


배치의 개념과 쓰는이유

개념: 경사하강법이 실행되어 가중치가 업데이트 되는 데이터의 양

쓰는이유: 한번에 모든데이터를 가지고 경사하강법을 실행하게되면 데이터의 양이 많아짐에 따라 시간이 많이걸리게됨

신기한점: 배치크기는 보통 2의 제곱수를 사용하는데, cpu와 gpu의 메모리가 2의 배수이기때문에 송수신 효율을 높일수있다고함

이터레이션과 배치사이즈의 관계

이터레이션: 1에포크당 가중치 업데이트 횟수

배치사이즈: 한번에 학습하는 데이터의 양

예를들어 2000개의 데이터에서 배치사이즈가 200이라면 이터레이션은 10이다

dataset과 dataloader

dataset 말그대로 데이터를 정의후(x와 y) dataloader에 전달 dataloder에서는 배치사이즈, shuffle 유무등을 설정할수있음

tensordataset을 이용한 예시

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

c:\Users\dodo7\miniconda3\envs\lesa4\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [11]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [12]:
dataset = TensorDataset(x_train, y_train)

In [13]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [14]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [15]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader): # 배치사이즈만큼 공급
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 23512.417969
Epoch    0/20 Batch 2/3 Cost: 8554.804688
Epoch    0/20 Batch 3/3 Cost: 1487.473633
Epoch    1/20 Batch 1/3 Cost: 743.667114
Epoch    1/20 Batch 2/3 Cost: 315.634247
Epoch    1/20 Batch 3/3 Cost: 135.355347
Epoch    2/20 Batch 1/3 Cost: 23.472504
Epoch    2/20 Batch 2/3 Cost: 2.992539
Epoch    2/20 Batch 3/3 Cost: 4.563807
Epoch    3/20 Batch 1/3 Cost: 1.188855
Epoch    3/20 Batch 2/3 Cost: 0.039677
Epoch    3/20 Batch 3/3 Cost: 2.651596
Epoch    4/20 Batch 1/3 Cost: 1.102763
Epoch    4/20 Batch 2/3 Cost: 0.785210
Epoch    4/20 Batch 3/3 Cost: 0.428983
Epoch    5/20 Batch 1/3 Cost: 0.625599
Epoch    5/20 Batch 2/3 Cost: 0.845041
Epoch    5/20 Batch 3/3 Cost: 1.253398
Epoch    6/20 Batch 1/3 Cost: 1.333785
Epoch    6/20 Batch 2/3 Cost: 0.644989
Epoch    6/20 Batch 3/3 Cost: 0.413338
Epoch    7/20 Batch 1/3 Cost: 0.809577
Epoch    7/20 Batch 2/3 Cost: 0.382057
Epoch    7/20 Batch 3/3 Cost: 2.372849
Epoch    8/20 Batch 1/3 Cost: 1.187758
Epoch   

In [16]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.0443]], grad_fn=<AddmmBackward0>)


커스텀 데이터셋

In [17]:
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

커스텀 데이터셋을 만들때 가장 기본적인 뼈대는 다음과 같다
  
  
  def __init__(self):

  def __len__(self):

  def __getitem__(self, idx): 

In [19]:
# Dataset 상속
class CustomDataset(Dataset): 
  def __init__(self): # 데이터셋의 전처리를 해주는 부분
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self): # 데이터셋의 길이. 즉, 총 샘플의 수를 적어주는 부분
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx): # 데이터셋에서 특정 1개의 샘플을 가져오는 함수
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [20]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [21]:
model = torch.nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))